approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

packageExtensions:
  "@docusaurus/plugin-ideal-image@*":
    dependencies:
      prop-types: "*"
